fix

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -53,17 +53,22 @@ validate_executable_format() {
     else
         EXECUTABLE_FORMAT="ELF"
     fi
-    if [[ "$GOARCH" == "amd64" && "$file_output" != *"x86-64"* ]]; then
-      echo "Error: ${EXECUTABLE} is not a valid x86-64 ELF binary"
-      exit 1
-    else
+
+    # Checking for architecture
+    if [[ "$GOARCH" == "amd64" ]]; then
+      if [[ "$file_output" != *"x86-64"* ]]; then
+        echo "Error: ${EXECUTABLE} is not a valid x86-64 ELF binary"
+        exit 1
+      else
         EXECUTABLE_ARCH="x86-64"
-    fi
-    if [[ "$GOARCH" == "arm64" && "$file_output" != *"ARM aarch64"* ]]; then
-      echo "Error: ${EXECUTABLE} is not a valid ARM aarch64 ELF binary"
-      exit 1
-    else
+      fi
+    elif [[ "$GOARCH" == "arm64" ]]; then
+      if [[ "$file_output" != *"ARM aarch64"* ]]; then
+        echo "Error: ${EXECUTABLE} is not a valid ARM aarch64 ELF binary"
+        exit 1
+      else
         EXECUTABLE_ARCH="ARM aarch64"
+      fi
     fi
   fi
 
@@ -76,17 +81,22 @@ validate_executable_format() {
     else
         EXECUTABLE_FORMAT="Mach-O"
     fi
-    if [[ "$GOARCH" == "amd64" && "$file_output" != *"x86_64"* ]]; then
-      echo "Error: ${EXECUTABLE} is not a valid x86 Mach-O binary"
-      exit 1
-    else
+
+    # Checking for architecture
+    if [[ "$GOARCH" == "amd64" ]]; then
+      if [[ "$file_output" != *"x86_64"* ]]; then
+        echo "Error: ${EXECUTABLE} is not a valid x86 Mach-O binary"
+        exit 1
+      else
         EXECUTABLE_ARCH="x86_64"
-    fi
-    if [[ "$GOARCH" == "arm64" && "$file_output" != *"arm64"* ]]; then
-      echo "Error: ${EXECUTABLE} is not a valid arm64 Mach-O binary"
-      exit 1
-    else
-      EXECUTABLE_ARCH="arm64"
+      fi
+    elif [[ "$GOARCH" == "arm64" ]]; then
+      if [[ "$file_output" != *"arm64"* ]]; then
+        echo "Error: ${EXECUTABLE} is not a valid arm64 Mach-O binary"
+        exit 1
+      else
+        EXECUTABLE_ARCH="arm64"
+      fi
     fi
   fi
 
