gets linux installer working with libpcap on ubuntu and fedora

diff --git a/linux-installer/deb-templates/postinst.tmpl b/linux-installer/deb-templates/postinst.tmpl
--- a/linux-installer/deb-templates/postinst.tmpl
+++ b/linux-installer/deb-templates/postinst.tmpl
@@ -16,6 +16,27 @@ chmod 0755 "{{ .BinFile }}"
 chown root:root "{{ .SystemdServiceFilePath }}"
 chmod 0644 "{{ .SystemdServiceFilePath }}"
 
+is_libpcap_installed() {
+    echo "Checking for libpcap installation"
+    if dpkg -l | grep -E '^ii[[:space:]]+libpcap0\.8' > /dev/null; then
+        echo "Found libpcap via package manager"
+        return 0
+    fi
+
+    echo "libpcap not found."
+    return 1
+}
+
+is_libpcap_installed
+libpcap_installed=$?
+
+if [ $libpcap_installed -eq 0 ]; then
+    echo "libpcap is installed, proceeding with installation"
+else
+    echo "libpcap is NOT installed. Please install libpcap0.8 before continuing."
+    exit 1
+fi
+
 # Prompt user for install key if not provided
 if [ ! -f "{{ .BootstrapFile }}" ]; then
     echo "Please enter the install key:"
diff --git a/linux-installer/rpm-templates/packet-sentry-agent.spec.tmpl b/linux-installer/rpm-templates/packet-sentry-agent.spec.tmpl
--- a/linux-installer/rpm-templates/packet-sentry-agent.spec.tmpl
+++ b/linux-installer/rpm-templates/packet-sentry-agent.spec.tmpl
@@ -26,6 +26,27 @@ install -m 644 %{_sourcedir}/{{ .Name }}.service %{buildroot}{{ .ServiceDestDir 
 %attr(644, root, root) {{ .ServiceDestDir }}/{{ .Name }}.service
 
 %post
+is_libpcap_installed() {
+    echo "Checking for libpcap installation"
+    if rpm -q libpcap | grep -E '^libpcap-[0-9\.\-]+(\.fc[0-9]+)?\.([xX]86_64|aarch64)$' > /dev/null; then
+        echo "Found libpcap via package manager"
+        return 0
+    fi
+
+    echo "libpcap not found."
+    return 1
+}
+
+is_libpcap_installed
+libpcap_installed=$?
+
+if [ $libpcap_installed -eq 0 ]; then
+    echo "libpcap is installed, proceeding with installation"
+else
+    echo "libpcap is NOT installed. Please install libpcap0.8 before continuing."
+    exit 1
+fi
+
 systemctl daemon-reload
 systemctl enable {{ .Name }}.service
 systemctl start {{ .Name }}.service || :
